from selenium import webdriver
import time
import names
import random
import string

# need to run 'pip install names'

# generate a random string of fixed length with
def randomString(stringLength=10):
    letters = string.ascii_letters
    return ''.join(random.choice(letters) for i in range(stringLength))+"!"

# create chrome driver and open google signup page
chrome_path = r"C:\Users\samue\Desktop\python\Discord-Account-Maker\chromedriver.exe"
driver = webdriver.Chrome(chrome_path)

# TODO: pick a different email address than gmail, since they require phone verification

driver.get('https://accounts.google.com/SignUp')

# generate user data
firstName = names.get_first_name()
lastName = names.get_last_name()
password = randomString()

print(password)

# send name data to form
driver.find_element_by_name("firstName").send_keys(firstName)
driver.find_element_by_name("lastName").send_keys(lastName)

# wait for form to autogenerate email address
# TODO: generate own email address from last and first name instead of gmail autogen
time.sleep(2.5)

# send password data to form
driver.find_element_by_name("Passwd").send_keys(password)
driver.find_element_by_name("ConfirmPasswd").send_keys(password)

# record email address generated by google form
emailAddress = driver.find_element_by_name("Username").get_attribute("value")

print(emailAddress)

# write email data to text file
open("emailData.txt","a").write(firstName+","+lastName+","+emailAddress+"@gmail.com"+"\n")

#click next button
driver.find_element_by_id("accountDetailsNext").click()
